### ISSUE TITLE
interface conversion: runtime.Object is nil, not *v1.Deployment

### ISSUE THREAD

**Issue by snebel29** [snebel29/kwatchman#10]
Ran kubewatch on this [commit](https://github.com/snebel29/kwatchman/commit/35d1771ffc0ab7b38c9c0072f725c591de709cc2) for a while and end up with a panic

```
ERROR: logging before flag.Parse: E0527 13:01:45.664802   44194 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1d12c40), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x1e1f460), missingMethod:""} (interface conversion: runtime.Object is nil, not *v1.Deployment)
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/asm_amd64.s:522
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/iface.go:248
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/iface.go:258
/Users/svennebel/go/src/github.com/snebel29/kwatchman/internal/pkg/watcher/k8s/resources/resources.go:39
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/handler/handler.go:42
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:346
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:280
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:252
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:228
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:212
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:212
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/asm_amd64.s:1333
panic: interface conversion: runtime.Object is nil, not *v1.Deployment [recovered]
	panic: interface conversion: runtime.Object is nil, not *v1.Deployment

goroutine 10 [running]:
github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1d03840, 0xc000321a40)
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
github.com/snebel29/kwatchman/internal/pkg/watcher/k8s/resources.NewK8sDeploymentWatcher.func3(0x1fa2080, 0xc000321a10, 0xc0002c3780, 0x1b12220, 0xc00043ffc0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/internal/pkg/watcher/k8s/resources/resources.go:39 +0x10e
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/handler.(*HandlerFunc).Delete(0xc0002f61f0, 0x1fa2080, 0xc000321a10, 0xc0002c3780, 0xc0003bcb00, 0x1fb3a00)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/handler/handler.go:42 +0x51
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).handleDelete(0xc00012c000, 0x1fa2080, 0xc000321a10, 0xc0002c3780, 0x0, 0x0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:346 +0x466
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).processJob(0xc00012c000, 0x1fa2080, 0xc0003219e0, 0xc0002c3780, 0x2a0cd40, 0xc0003219e0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:280 +0x14e
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).getAndProcessNextJob(0xc00012c000, 0xc0001fe100)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:252 +0x1f0
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).runWorker(0xc00012c000)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:228 +0x2b
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).runWorker-fm()
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:212 +0x2a
github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00046dfb0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000797fb0, 0x3b9aca00, 0x0, 0x1, 0xc00009a7e0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00046dfb0, 0x3b9aca00, 0xc00009a7e0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).run.func1(0xc00012c000, 0xc00009a7e0)
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:212 +0x5c
created by github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller.(*generic).run
	/Users/svennebel/go/src/github.com/snebel29/kwatchman/vendor/github.com/snebel29/kooper/operator/controller/generic.go:211 +0x1e8
```

**Comment by snebel29** [comment]
Pushed [commit](https://github.com/snebel29/kwatchman/pull/9/commits/48426dc93285a897acc604fd1ca89c45d4edf11c) to workaround the type assertion cast panic, although it's yet not clear why listWatcher is sending a nil `runtime.Object` object

**Comment by snebel29** [comment]
Feels like the problem is Delete handler not being handler correctly, more specifically

https://github.com/snebel29/kwatchman/blob/ac68ff85351f037194c84bf7a74e9cf37b72d077/vendor/github.com/snebel29/kooper/operator/controller/generic.go#L278-L284

When there is a delete event, `evt.Object` is not assigned therefore Object keeps its zero value (nil), this also raises the need for handling delete function differently?

https://github.com/snebel29/kwatchman/blob/ac68ff85351f037194c84bf7a74e9cf37b72d077/internal/pkg/watcher/k8s/resources/resources.go#L50-L53

Not necessary above, but at least handlers should taker into consideration Add, Update and Delete event types
